### PR TITLE
Pixtral

### PR DESCRIPTION
**Pull request by patrickvonplaten**

### CODE REVIEW

**Comment by patrickvonplaten** [comment]
@SocketSecurity ignore-all

**Review by timlacroix — APPROVED** [review]
lgtm

**Comment by EwoutH** [comment]
Really awesome! Are there docs or a guide available?

**Comment by COWI-MI** [comment]
> Really awesome! Are there docs or a guide available?
check https://github.com/mistralai/mistral-common/releases/tag/v1.4.0

**Pull request merged**
