### PR TITLE
Update sentencepiece to 0.2.0

### PR DESCRIPTION
**Pull request by yiwei-w**
Update `sentencepiece` from 0.1.99 to 0.2.0 (the latest version).

### CODE REVIEW

**Comment by RoiGlinik** [comment]
Is there anything I can do to help merge this?

**Comment by zffocussss** [comment]
yes we need this upgrade as installation will be interrupted  with python 3.12 in debian.

**Comment by pandora-s-git** [comment]
This update has already been done in a previous recent commit 😉

**Comment by zffocussss** [comment]
> This update has already been done in a previous recent commit 😉

yes we all know it,but we need a new version/tag to pip install.

**Comment by yiwei-w** [comment]
Close the request as `sentencepiece` has already been updated in main

**Pull request closed without merging**
